spring:
  application.name: ApiDoc
  datasource:
    url: jdbc:mysql://localhost:3306/doc?createDatabaseIfNotExist=true
    username: root
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validateOnMigrate: true
server:
  port: 8087
file:
  storage:
    location:  C:/Users/Ouissal/Desktop/docsStorage


