CREATE TABLE DOCUMENT
(
    ID_DOCUMENT   INT AUTO_INCREMENT PRIMARY KEY,
    NOM           VARCHAR(255),
    TYPE          VARCHAR(255),
    DATE_CREATION DATE,
    URL_DOCUMENT  VARCHAR(1000)
)