CREATE TABLE AUTORISATION
(
    ID_DOCUMENT INT,
    ID_USER INT,
    DROIT_ACCES VARCHAR(255),
    FOREIGN KEY (ID_DOCUMENT) REFERENCES DOCUMENT(ID_DOCUMENT),
    FOREIGN KEY (ID_USER) REFERENCES doc_user(idUser),
    PRIMARY KEY (ID_DOCUMENT,ID_USER)
)